controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

collaborator_new:
    path: /ajouter/{id}
    controller: App\Controller\CollaboratorController::new
    methods: GET|POST
    requirements:
        id: '\d+'


load.events:
    path: /load-events
    controller: App\Controller\CalendarController::loadEvents
    methods: GET|POST
